version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - misspell
    - nilerr
    - revive
    - testifylint
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports
