// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gophkeeper/v1/auth.proto

package gophkeeperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest contains authentication data and a client-encrypted data key.
type RegisterRequest struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login                *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password             *string                `protobuf:"bytes,2,opt,name=password"`
	xxx_hidden_EncryptedDataKey     []byte                 `protobuf:"bytes,3,opt,name=encrypted_data_key,json=encryptedDataKey"`
	xxx_hidden_KeySalt              []byte                 `protobuf:"bytes,4,opt,name=key_salt,json=keySalt"`
	xxx_hidden_KeyNonce             []byte                 `protobuf:"bytes,5,opt,name=key_nonce,json=keyNonce"`
	xxx_hidden_KeyDerivationVersion uint32                 `protobuf:"varint,6,opt,name=key_derivation_version,json=keyDerivationVersion"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetEncryptedDataKey() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedDataKey
	}
	return nil
}

func (x *RegisterRequest) GetKeySalt() []byte {
	if x != nil {
		return x.xxx_hidden_KeySalt
	}
	return nil
}

func (x *RegisterRequest) GetKeyNonce() []byte {
	if x != nil {
		return x.xxx_hidden_KeyNonce
	}
	return nil
}

func (x *RegisterRequest) GetKeyDerivationVersion() uint32 {
	if x != nil {
		return x.xxx_hidden_KeyDerivationVersion
	}
	return 0
}

func (x *RegisterRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *RegisterRequest) SetEncryptedDataKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedDataKey = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *RegisterRequest) SetKeySalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_KeySalt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *RegisterRequest) SetKeyNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_KeyNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *RegisterRequest) SetKeyDerivationVersion(v uint32) {
	x.xxx_hidden_KeyDerivationVersion = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *RegisterRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterRequest) HasEncryptedDataKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RegisterRequest) HasKeySalt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RegisterRequest) HasKeyNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *RegisterRequest) HasKeyDerivationVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *RegisterRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *RegisterRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

func (x *RegisterRequest) ClearEncryptedDataKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EncryptedDataKey = nil
}

func (x *RegisterRequest) ClearKeySalt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_KeySalt = nil
}

func (x *RegisterRequest) ClearKeyNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_KeyNonce = nil
}

func (x *RegisterRequest) ClearKeyDerivationVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_KeyDerivationVersion = 0
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login                *string
	Password             *string
	EncryptedDataKey     []byte
	KeySalt              []byte
	KeyNonce             []byte
	KeyDerivationVersion *uint32
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Password = b.Password
	}
	if b.EncryptedDataKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_EncryptedDataKey = b.EncryptedDataKey
	}
	if b.KeySalt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_KeySalt = b.KeySalt
	}
	if b.KeyNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_KeyNonce = b.KeyNonce
	}
	if b.KeyDerivationVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_KeyDerivationVersion = *b.KeyDerivationVersion
	}
	return m0
}

// RegisterResponse contains a newly created authenticated session.
type RegisterResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Session *Session               `protobuf:"bytes,1,opt,name=session"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetSession() *Session {
	if x != nil {
		return x.xxx_hidden_Session
	}
	return nil
}

func (x *RegisterResponse) SetSession(v *Session) {
	x.xxx_hidden_Session = v
}

func (x *RegisterResponse) HasSession() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Session != nil
}

func (x *RegisterResponse) ClearSession() {
	x.xxx_hidden_Session = nil
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Session *Session
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Session = b.Session
	return m0
}

// LoginRequest contains account credentials.
type LoginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *LoginRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Password *string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

// LoginResponse contains a session and the material required to unlock the
// client-encrypted data key locally.
type LoginResponse struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Session              *Session               `protobuf:"bytes,1,opt,name=session"`
	xxx_hidden_EncryptedDataKey     []byte                 `protobuf:"bytes,2,opt,name=encrypted_data_key,json=encryptedDataKey"`
	xxx_hidden_KeySalt              []byte                 `protobuf:"bytes,3,opt,name=key_salt,json=keySalt"`
	xxx_hidden_KeyNonce             []byte                 `protobuf:"bytes,4,opt,name=key_nonce,json=keyNonce"`
	xxx_hidden_KeyDerivationVersion uint32                 `protobuf:"varint,5,opt,name=key_derivation_version,json=keyDerivationVersion"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetSession() *Session {
	if x != nil {
		return x.xxx_hidden_Session
	}
	return nil
}

func (x *LoginResponse) GetEncryptedDataKey() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedDataKey
	}
	return nil
}

func (x *LoginResponse) GetKeySalt() []byte {
	if x != nil {
		return x.xxx_hidden_KeySalt
	}
	return nil
}

func (x *LoginResponse) GetKeyNonce() []byte {
	if x != nil {
		return x.xxx_hidden_KeyNonce
	}
	return nil
}

func (x *LoginResponse) GetKeyDerivationVersion() uint32 {
	if x != nil {
		return x.xxx_hidden_KeyDerivationVersion
	}
	return 0
}

func (x *LoginResponse) SetSession(v *Session) {
	x.xxx_hidden_Session = v
}

func (x *LoginResponse) SetEncryptedDataKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedDataKey = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *LoginResponse) SetKeySalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_KeySalt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *LoginResponse) SetKeyNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_KeyNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *LoginResponse) SetKeyDerivationVersion(v uint32) {
	x.xxx_hidden_KeyDerivationVersion = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *LoginResponse) HasSession() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Session != nil
}

func (x *LoginResponse) HasEncryptedDataKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginResponse) HasKeySalt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *LoginResponse) HasKeyNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *LoginResponse) HasKeyDerivationVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *LoginResponse) ClearSession() {
	x.xxx_hidden_Session = nil
}

func (x *LoginResponse) ClearEncryptedDataKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EncryptedDataKey = nil
}

func (x *LoginResponse) ClearKeySalt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_KeySalt = nil
}

func (x *LoginResponse) ClearKeyNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_KeyNonce = nil
}

func (x *LoginResponse) ClearKeyDerivationVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_KeyDerivationVersion = 0
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Session              *Session
	EncryptedDataKey     []byte
	KeySalt              []byte
	KeyNonce             []byte
	KeyDerivationVersion *uint32
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Session = b.Session
	if b.EncryptedDataKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_EncryptedDataKey = b.EncryptedDataKey
	}
	if b.KeySalt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_KeySalt = b.KeySalt
	}
	if b.KeyNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_KeyNonce = b.KeyNonce
	}
	if b.KeyDerivationVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_KeyDerivationVersion = *b.KeyDerivationVersion
	}
	return m0
}

// LogoutRequest revokes the session identified by authorization metadata.
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LogoutRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LogoutRequest_builder) Build() *LogoutRequest {
	m0 := &LogoutRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// LogoutResponse confirms successful session revocation.
type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LogoutResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LogoutResponse_builder) Build() *LogoutResponse {
	m0 := &LogoutResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Session contains the bearer token returned only to the authenticated client.
type Session struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Session) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *Session) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Session) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *Session) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Session) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *Session) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *Session) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

type Session_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token     *string
	ExpiresAt *timestamppb.Timestamp
}

func (b0 Session_builder) Build() *Session {
	m0 := &Session{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Token = b.Token
	}
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	return m0
}

var File_gophkeeper_v1_auth_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18gophkeeper/v1/auth.proto\x12\rgophkeeper.v1\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12,\n" +
	"\x12encrypted_data_key\x18\x03 \x01(\fR\x10encryptedDataKey\x12\x19\n" +
	"\bkey_salt\x18\x04 \x01(\fR\akeySalt\x12\x1b\n" +
	"\tkey_nonce\x18\x05 \x01(\fR\bkeyNonce\x124\n" +
	"\x16key_derivation_version\x18\x06 \x01(\rR\x14keyDerivationVersion\"D\n" +
	"\x10RegisterResponse\x120\n" +
	"\asession\x18\x01 \x01(\v2\x16.gophkeeper.v1.SessionR\asession\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xdd\x01\n" +
	"\rLoginResponse\x120\n" +
	"\asession\x18\x01 \x01(\v2\x16.gophkeeper.v1.SessionR\asession\x12,\n" +
	"\x12encrypted_data_key\x18\x02 \x01(\fR\x10encryptedDataKey\x12\x19\n" +
	"\bkey_salt\x18\x03 \x01(\fR\akeySalt\x12\x1b\n" +
	"\tkey_nonce\x18\x04 \x01(\fR\bkeyNonce\x124\n" +
	"\x16key_derivation_version\x18\x05 \x01(\rR\x14keyDerivationVersion\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"Z\n" +
	"\aSession\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\xe5\x01\n" +
	"\vAuthService\x12K\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1f.gophkeeper.v1.RegisterResponse\x12B\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1c.gophkeeper.v1.LoginResponse\x12E\n" +
	"\x06Logout\x12\x1c.gophkeeper.v1.LogoutRequest\x1a\x1d.gophkeeper.v1.LogoutResponseBJZ@github.com/sastromikus/gophkeeper/api/gophkeeper/v1;gophkeeperv1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gophkeeper_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gophkeeper_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: gophkeeper.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: gophkeeper.v1.RegisterResponse
	(*LoginRequest)(nil),          // 2: gophkeeper.v1.LoginRequest
	(*LoginResponse)(nil),         // 3: gophkeeper.v1.LoginResponse
	(*LogoutRequest)(nil),         // 4: gophkeeper.v1.LogoutRequest
	(*LogoutResponse)(nil),        // 5: gophkeeper.v1.LogoutResponse
	(*Session)(nil),               // 6: gophkeeper.v1.Session
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_gophkeeper_v1_auth_proto_depIdxs = []int32{
	6, // 0: gophkeeper.v1.RegisterResponse.session:type_name -> gophkeeper.v1.Session
	6, // 1: gophkeeper.v1.LoginResponse.session:type_name -> gophkeeper.v1.Session
	7, // 2: gophkeeper.v1.Session.expires_at:type_name -> google.protobuf.Timestamp
	0, // 3: gophkeeper.v1.AuthService.Register:input_type -> gophkeeper.v1.RegisterRequest
	2, // 4: gophkeeper.v1.AuthService.Login:input_type -> gophkeeper.v1.LoginRequest
	4, // 5: gophkeeper.v1.AuthService.Logout:input_type -> gophkeeper.v1.LogoutRequest
	1, // 6: gophkeeper.v1.AuthService.Register:output_type -> gophkeeper.v1.RegisterResponse
	3, // 7: gophkeeper.v1.AuthService.Login:output_type -> gophkeeper.v1.LoginResponse
	5, // 8: gophkeeper.v1.AuthService.Logout:output_type -> gophkeeper.v1.LogoutResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_auth_proto_init() }
func file_gophkeeper_v1_auth_proto_init() {
	if File_gophkeeper_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_auth_proto_rawDesc), len(file_gophkeeper_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_v1_auth_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_auth_proto_depIdxs,
		MessageInfos:      file_gophkeeper_v1_auth_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_auth_proto = out.File
	file_gophkeeper_v1_auth_proto_goTypes = nil
	file_gophkeeper_v1_auth_proto_depIdxs = nil
}
