// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gophkeeper/v1/vault.proto

package gophkeeperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecordType identifies the plaintext schema encrypted inside a record.
type RecordType int32

const (
	RecordType_RECORD_TYPE_UNSPECIFIED RecordType = 0
	RecordType_RECORD_TYPE_CREDENTIALS RecordType = 1
	RecordType_RECORD_TYPE_TEXT        RecordType = 2
	RecordType_RECORD_TYPE_BINARY      RecordType = 3
	RecordType_RECORD_TYPE_BANK_CARD   RecordType = 4
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "RECORD_TYPE_UNSPECIFIED",
		1: "RECORD_TYPE_CREDENTIALS",
		2: "RECORD_TYPE_TEXT",
		3: "RECORD_TYPE_BINARY",
		4: "RECORD_TYPE_BANK_CARD",
	}
	RecordType_value = map[string]int32{
		"RECORD_TYPE_UNSPECIFIED": 0,
		"RECORD_TYPE_CREDENTIALS": 1,
		"RECORD_TYPE_TEXT":        2,
		"RECORD_TYPE_BINARY":      3,
		"RECORD_TYPE_BANK_CARD":   4,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_vault_proto_enumTypes[0].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_vault_proto_enumTypes[0]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Record contains encrypted payloads and server-managed synchronization data.
// The user ID is deliberately omitted and is taken from authorization metadata.
type Record struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Type              RecordType             `protobuf:"varint,2,opt,name=type,enum=gophkeeper.v1.RecordType"`
	xxx_hidden_EncryptedPayload  []byte                 `protobuf:"bytes,3,opt,name=encrypted_payload,json=encryptedPayload"`
	xxx_hidden_EncryptedMetadata []byte                 `protobuf:"bytes,4,opt,name=encrypted_metadata,json=encryptedMetadata"`
	xxx_hidden_PayloadNonce      []byte                 `protobuf:"bytes,5,opt,name=payload_nonce,json=payloadNonce"`
	xxx_hidden_MetadataNonce     []byte                 `protobuf:"bytes,6,opt,name=metadata_nonce,json=metadataNonce"`
	xxx_hidden_Version           int64                  `protobuf:"varint,7,opt,name=version"`
	xxx_hidden_Revision          int64                  `protobuf:"varint,8,opt,name=revision"`
	xxx_hidden_CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_DeletedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Record) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Record) GetType() RecordType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *Record) GetEncryptedPayload() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedPayload
	}
	return nil
}

func (x *Record) GetEncryptedMetadata() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedMetadata
	}
	return nil
}

func (x *Record) GetPayloadNonce() []byte {
	if x != nil {
		return x.xxx_hidden_PayloadNonce
	}
	return nil
}

func (x *Record) GetMetadataNonce() []byte {
	if x != nil {
		return x.xxx_hidden_MetadataNonce
	}
	return nil
}

func (x *Record) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Record) GetRevision() int64 {
	if x != nil {
		return x.xxx_hidden_Revision
	}
	return 0
}

func (x *Record) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Record) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Record) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DeletedAt
	}
	return nil
}

func (x *Record) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *Record) SetType(v RecordType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 11)
}

func (x *Record) SetEncryptedPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *Record) SetEncryptedMetadata(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedMetadata = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *Record) SetPayloadNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PayloadNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 11)
}

func (x *Record) SetMetadataNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_MetadataNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
}

func (x *Record) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 11)
}

func (x *Record) SetRevision(v int64) {
	x.xxx_hidden_Revision = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 11)
}

func (x *Record) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Record) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Record) SetDeletedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_DeletedAt = v
}

func (x *Record) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Record) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Record) HasEncryptedPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Record) HasEncryptedMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Record) HasPayloadNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Record) HasMetadataNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Record) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Record) HasRevision() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Record) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Record) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Record) HasDeletedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeletedAt != nil
}

func (x *Record) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Record) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *Record) ClearEncryptedPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EncryptedPayload = nil
}

func (x *Record) ClearEncryptedMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_EncryptedMetadata = nil
}

func (x *Record) ClearPayloadNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PayloadNonce = nil
}

func (x *Record) ClearMetadataNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_MetadataNonce = nil
}

func (x *Record) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Version = 0
}

func (x *Record) ClearRevision() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Revision = 0
}

func (x *Record) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Record) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *Record) ClearDeletedAt() {
	x.xxx_hidden_DeletedAt = nil
}

type Record_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                *string
	Type              *RecordType
	EncryptedPayload  []byte
	EncryptedMetadata []byte
	PayloadNonce      []byte
	MetadataNonce     []byte
	Version           *int64
	Revision          *int64
	CreatedAt         *timestamppb.Timestamp
	UpdatedAt         *timestamppb.Timestamp
	DeletedAt         *timestamppb.Timestamp
}

func (b0 Record_builder) Build() *Record {
	m0 := &Record{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_Id = b.Id
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 11)
		x.xxx_hidden_Type = *b.Type
	}
	if b.EncryptedPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_EncryptedPayload = b.EncryptedPayload
	}
	if b.EncryptedMetadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_EncryptedMetadata = b.EncryptedMetadata
	}
	if b.PayloadNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 11)
		x.xxx_hidden_PayloadNonce = b.PayloadNonce
	}
	if b.MetadataNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_MetadataNonce = b.MetadataNonce
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 11)
		x.xxx_hidden_Version = *b.Version
	}
	if b.Revision != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 11)
		x.xxx_hidden_Revision = *b.Revision
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_DeletedAt = b.DeletedAt
	return m0
}

// EncryptedRecordData contains client-produced encrypted record fields.
type EncryptedRecordData struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type              RecordType             `protobuf:"varint,1,opt,name=type,enum=gophkeeper.v1.RecordType"`
	xxx_hidden_EncryptedPayload  []byte                 `protobuf:"bytes,2,opt,name=encrypted_payload,json=encryptedPayload"`
	xxx_hidden_EncryptedMetadata []byte                 `protobuf:"bytes,3,opt,name=encrypted_metadata,json=encryptedMetadata"`
	xxx_hidden_PayloadNonce      []byte                 `protobuf:"bytes,4,opt,name=payload_nonce,json=payloadNonce"`
	xxx_hidden_MetadataNonce     []byte                 `protobuf:"bytes,5,opt,name=metadata_nonce,json=metadataNonce"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *EncryptedRecordData) Reset() {
	*x = EncryptedRecordData{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedRecordData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedRecordData) ProtoMessage() {}

func (x *EncryptedRecordData) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EncryptedRecordData) GetType() RecordType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *EncryptedRecordData) GetEncryptedPayload() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedPayload
	}
	return nil
}

func (x *EncryptedRecordData) GetEncryptedMetadata() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedMetadata
	}
	return nil
}

func (x *EncryptedRecordData) GetPayloadNonce() []byte {
	if x != nil {
		return x.xxx_hidden_PayloadNonce
	}
	return nil
}

func (x *EncryptedRecordData) GetMetadataNonce() []byte {
	if x != nil {
		return x.xxx_hidden_MetadataNonce
	}
	return nil
}

func (x *EncryptedRecordData) SetType(v RecordType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *EncryptedRecordData) SetEncryptedPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *EncryptedRecordData) SetEncryptedMetadata(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedMetadata = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *EncryptedRecordData) SetPayloadNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PayloadNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *EncryptedRecordData) SetMetadataNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_MetadataNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *EncryptedRecordData) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EncryptedRecordData) HasEncryptedPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EncryptedRecordData) HasEncryptedMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *EncryptedRecordData) HasPayloadNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *EncryptedRecordData) HasMetadataNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *EncryptedRecordData) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = RecordType_RECORD_TYPE_UNSPECIFIED
}

func (x *EncryptedRecordData) ClearEncryptedPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EncryptedPayload = nil
}

func (x *EncryptedRecordData) ClearEncryptedMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EncryptedMetadata = nil
}

func (x *EncryptedRecordData) ClearPayloadNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_PayloadNonce = nil
}

func (x *EncryptedRecordData) ClearMetadataNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_MetadataNonce = nil
}

type EncryptedRecordData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type              *RecordType
	EncryptedPayload  []byte
	EncryptedMetadata []byte
	PayloadNonce      []byte
	MetadataNonce     []byte
}

func (b0 EncryptedRecordData_builder) Build() *EncryptedRecordData {
	m0 := &EncryptedRecordData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Type = *b.Type
	}
	if b.EncryptedPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_EncryptedPayload = b.EncryptedPayload
	}
	if b.EncryptedMetadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_EncryptedMetadata = b.EncryptedMetadata
	}
	if b.PayloadNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_PayloadNonce = b.PayloadNonce
	}
	if b.MetadataNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_MetadataNonce = b.MetadataNonce
	}
	return m0
}

// CreateRecordRequest creates a record with a client-generated UUID.
type CreateRecordRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Data        *EncryptedRecordData   `protobuf:"bytes,2,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateRecordRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *CreateRecordRequest) GetData() *EncryptedRecordData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *CreateRecordRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateRecordRequest) SetData(v *EncryptedRecordData) {
	x.xxx_hidden_Data = v
}

func (x *CreateRecordRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateRecordRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *CreateRecordRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *CreateRecordRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

type CreateRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   *string
	Data *EncryptedRecordData
}

func (b0 CreateRecordRequest_builder) Build() *CreateRecordRequest {
	m0 := &CreateRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Data = b.Data
	return m0
}

// GetRecordRequest identifies a record owned by the authenticated user.
type GetRecordRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRecordRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetRecordRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetRecordRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetRecordRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type GetRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 GetRecordRequest_builder) Build() *GetRecordRequest {
	m0 := &GetRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

// ListRecordsRequest requests the current active vault contents.
type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListRecordsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListRecordsRequest_builder) Build() *ListRecordsRequest {
	m0 := &ListRecordsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// ListRecordsResponse contains active records only.
type ListRecordsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Records *[]*Record             `protobuf:"bytes,1,rep,name=records"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRecordsResponse) GetRecords() []*Record {
	if x != nil {
		if x.xxx_hidden_Records != nil {
			return *x.xxx_hidden_Records
		}
	}
	return nil
}

func (x *ListRecordsResponse) SetRecords(v []*Record) {
	x.xxx_hidden_Records = &v
}

type ListRecordsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Records []*Record
}

func (b0 ListRecordsResponse_builder) Build() *ListRecordsResponse {
	m0 := &ListRecordsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Records = &b.Records
	return m0
}

// UpdateRecordRequest replaces encrypted fields using optimistic locking.
type UpdateRecordRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id              *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion"`
	xxx_hidden_Data            *EncryptedRecordData   `protobuf:"bytes,3,opt,name=data"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRecordRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *UpdateRecordRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.xxx_hidden_ExpectedVersion
	}
	return 0
}

func (x *UpdateRecordRequest) GetData() *EncryptedRecordData {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *UpdateRecordRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *UpdateRecordRequest) SetExpectedVersion(v int64) {
	x.xxx_hidden_ExpectedVersion = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *UpdateRecordRequest) SetData(v *EncryptedRecordData) {
	x.xxx_hidden_Data = v
}

func (x *UpdateRecordRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateRecordRequest) HasExpectedVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateRecordRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *UpdateRecordRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *UpdateRecordRequest) ClearExpectedVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ExpectedVersion = 0
}

func (x *UpdateRecordRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

type UpdateRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id              *string
	ExpectedVersion *int64
	Data            *EncryptedRecordData
}

func (b0 UpdateRecordRequest_builder) Build() *UpdateRecordRequest {
	m0 := &UpdateRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	if b.ExpectedVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ExpectedVersion = *b.ExpectedVersion
	}
	x.xxx_hidden_Data = b.Data
	return m0
}

// DeleteRecordRequest deletes a record using optimistic locking.
type DeleteRecordRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id              *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRecordRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DeleteRecordRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.xxx_hidden_ExpectedVersion
	}
	return 0
}

func (x *DeleteRecordRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DeleteRecordRequest) SetExpectedVersion(v int64) {
	x.xxx_hidden_ExpectedVersion = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DeleteRecordRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteRecordRequest) HasExpectedVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteRecordRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *DeleteRecordRequest) ClearExpectedVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ExpectedVersion = 0
}

type DeleteRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id              *string
	ExpectedVersion *int64
}

func (b0 DeleteRecordRequest_builder) Build() *DeleteRecordRequest {
	m0 := &DeleteRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.ExpectedVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ExpectedVersion = *b.ExpectedVersion
	}
	return m0
}

// DeleteRecordResponse returns the server-created tombstone.
type DeleteRecordResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Record *Record                `protobuf:"bytes,1,opt,name=record"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteRecordResponse) Reset() {
	*x = DeleteRecordResponse{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordResponse) ProtoMessage() {}

func (x *DeleteRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRecordResponse) GetRecord() *Record {
	if x != nil {
		return x.xxx_hidden_Record
	}
	return nil
}

func (x *DeleteRecordResponse) SetRecord(v *Record) {
	x.xxx_hidden_Record = v
}

func (x *DeleteRecordResponse) HasRecord() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Record != nil
}

func (x *DeleteRecordResponse) ClearRecord() {
	x.xxx_hidden_Record = nil
}

type DeleteRecordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Record *Record
}

func (b0 DeleteRecordResponse_builder) Build() *DeleteRecordResponse {
	m0 := &DeleteRecordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Record = b.Record
	return m0
}

// RecordResponse wraps one record.
type RecordResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Record *Record                `protobuf:"bytes,1,opt,name=record"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordResponse) GetRecord() *Record {
	if x != nil {
		return x.xxx_hidden_Record
	}
	return nil
}

func (x *RecordResponse) SetRecord(v *Record) {
	x.xxx_hidden_Record = v
}

func (x *RecordResponse) HasRecord() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Record != nil
}

func (x *RecordResponse) ClearRecord() {
	x.xxx_hidden_Record = nil
}

type RecordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Record *Record
}

func (b0 RecordResponse_builder) Build() *RecordResponse {
	m0 := &RecordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Record = b.Record
	return m0
}

// SyncRecordsRequest uses a server revision as an exclusive cursor.
type SyncRecordsRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AfterRevision int64                  `protobuf:"varint,1,opt,name=after_revision,json=afterRevision"`
	xxx_hidden_Limit         uint32                 `protobuf:"varint,2,opt,name=limit"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SyncRecordsRequest) Reset() {
	*x = SyncRecordsRequest{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRecordsRequest) ProtoMessage() {}

func (x *SyncRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncRecordsRequest) GetAfterRevision() int64 {
	if x != nil {
		return x.xxx_hidden_AfterRevision
	}
	return 0
}

func (x *SyncRecordsRequest) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *SyncRecordsRequest) SetAfterRevision(v int64) {
	x.xxx_hidden_AfterRevision = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SyncRecordsRequest) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SyncRecordsRequest) HasAfterRevision() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SyncRecordsRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SyncRecordsRequest) ClearAfterRevision() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AfterRevision = 0
}

func (x *SyncRecordsRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

type SyncRecordsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AfterRevision *int64
	Limit         *uint32
}

func (b0 SyncRecordsRequest_builder) Build() *SyncRecordsRequest {
	m0 := &SyncRecordsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AfterRevision != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_AfterRevision = *b.AfterRevision
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Limit = *b.Limit
	}
	return m0
}

// SyncRecordsResponse contains ordered changes and the next durable cursor.
type SyncRecordsResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Records      *[]*Record             `protobuf:"bytes,1,rep,name=records"`
	xxx_hidden_NextRevision int64                  `protobuf:"varint,2,opt,name=next_revision,json=nextRevision"`
	xxx_hidden_HasMore      bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SyncRecordsResponse) Reset() {
	*x = SyncRecordsResponse{}
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRecordsResponse) ProtoMessage() {}

func (x *SyncRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_vault_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncRecordsResponse) GetRecords() []*Record {
	if x != nil {
		if x.xxx_hidden_Records != nil {
			return *x.xxx_hidden_Records
		}
	}
	return nil
}

func (x *SyncRecordsResponse) GetNextRevision() int64 {
	if x != nil {
		return x.xxx_hidden_NextRevision
	}
	return 0
}

func (x *SyncRecordsResponse) GetHasMore() bool {
	if x != nil {
		return x.xxx_hidden_HasMore
	}
	return false
}

func (x *SyncRecordsResponse) SetRecords(v []*Record) {
	x.xxx_hidden_Records = &v
}

func (x *SyncRecordsResponse) SetNextRevision(v int64) {
	x.xxx_hidden_NextRevision = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *SyncRecordsResponse) SetHasMore(v bool) {
	x.xxx_hidden_HasMore = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *SyncRecordsResponse) HasNextRevision() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SyncRecordsResponse) HasHasMore() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SyncRecordsResponse) ClearNextRevision() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextRevision = 0
}

func (x *SyncRecordsResponse) ClearHasMore() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_HasMore = false
}

type SyncRecordsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Records      []*Record
	NextRevision *int64
	HasMore      *bool
}

func (b0 SyncRecordsResponse_builder) Build() *SyncRecordsResponse {
	m0 := &SyncRecordsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Records = &b.Records
	if b.NextRevision != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_NextRevision = *b.NextRevision
	}
	if b.HasMore != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_HasMore = *b.HasMore
	}
	return m0
}

var File_gophkeeper_v1_vault_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_vault_proto_rawDesc = "" +
	"\n" +
	"\x19gophkeeper/v1/vault.proto\x12\rgophkeeper.v1\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x03\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.RecordTypeR\x04type\x12+\n" +
	"\x11encrypted_payload\x18\x03 \x01(\fR\x10encryptedPayload\x12-\n" +
	"\x12encrypted_metadata\x18\x04 \x01(\fR\x11encryptedMetadata\x12#\n" +
	"\rpayload_nonce\x18\x05 \x01(\fR\fpayloadNonce\x12%\n" +
	"\x0emetadata_nonce\x18\x06 \x01(\fR\rmetadataNonce\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x1a\n" +
	"\brevision\x18\b \x01(\x03R\brevision\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xec\x01\n" +
	"\x13EncryptedRecordData\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.gophkeeper.v1.RecordTypeR\x04type\x12+\n" +
	"\x11encrypted_payload\x18\x02 \x01(\fR\x10encryptedPayload\x12-\n" +
	"\x12encrypted_metadata\x18\x03 \x01(\fR\x11encryptedMetadata\x12#\n" +
	"\rpayload_nonce\x18\x04 \x01(\fR\fpayloadNonce\x12%\n" +
	"\x0emetadata_nonce\x18\x05 \x01(\fR\rmetadataNonce\"]\n" +
	"\x13CreateRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04data\x18\x02 \x01(\v2\".gophkeeper.v1.EncryptedRecordDataR\x04data\"\"\n" +
	"\x10GetRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12ListRecordsRequest\"F\n" +
	"\x13ListRecordsResponse\x12/\n" +
	"\arecords\x18\x01 \x03(\v2\x15.gophkeeper.v1.RecordR\arecords\"\x88\x01\n" +
	"\x13UpdateRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\x126\n" +
	"\x04data\x18\x03 \x01(\v2\".gophkeeper.v1.EncryptedRecordDataR\x04data\"P\n" +
	"\x13DeleteRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\"E\n" +
	"\x14DeleteRecordResponse\x12-\n" +
	"\x06record\x18\x01 \x01(\v2\x15.gophkeeper.v1.RecordR\x06record\"?\n" +
	"\x0eRecordResponse\x12-\n" +
	"\x06record\x18\x01 \x01(\v2\x15.gophkeeper.v1.RecordR\x06record\"Q\n" +
	"\x12SyncRecordsRequest\x12%\n" +
	"\x0eafter_revision\x18\x01 \x01(\x03R\rafterRevision\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"\x86\x01\n" +
	"\x13SyncRecordsResponse\x12/\n" +
	"\arecords\x18\x01 \x03(\v2\x15.gophkeeper.v1.RecordR\arecords\x12#\n" +
	"\rnext_revision\x18\x02 \x01(\x03R\fnextRevision\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore*\x8f\x01\n" +
	"\n" +
	"RecordType\x12\x1b\n" +
	"\x17RECORD_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RECORD_TYPE_CREDENTIALS\x10\x01\x12\x14\n" +
	"\x10RECORD_TYPE_TEXT\x10\x02\x12\x16\n" +
	"\x12RECORD_TYPE_BINARY\x10\x03\x12\x19\n" +
	"\x15RECORD_TYPE_BANK_CARD\x10\x042\x86\x04\n" +
	"\fVaultService\x12Q\n" +
	"\fCreateRecord\x12\".gophkeeper.v1.CreateRecordRequest\x1a\x1d.gophkeeper.v1.RecordResponse\x12K\n" +
	"\tGetRecord\x12\x1f.gophkeeper.v1.GetRecordRequest\x1a\x1d.gophkeeper.v1.RecordResponse\x12T\n" +
	"\vListRecords\x12!.gophkeeper.v1.ListRecordsRequest\x1a\".gophkeeper.v1.ListRecordsResponse\x12Q\n" +
	"\fUpdateRecord\x12\".gophkeeper.v1.UpdateRecordRequest\x1a\x1d.gophkeeper.v1.RecordResponse\x12W\n" +
	"\fDeleteRecord\x12\".gophkeeper.v1.DeleteRecordRequest\x1a#.gophkeeper.v1.DeleteRecordResponse\x12T\n" +
	"\vSyncRecords\x12!.gophkeeper.v1.SyncRecordsRequest\x1a\".gophkeeper.v1.SyncRecordsResponseBJZ@github.com/sastromikus/gophkeeper/api/gophkeeper/v1;gophkeeperv1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gophkeeper_v1_vault_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gophkeeper_v1_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gophkeeper_v1_vault_proto_goTypes = []any{
	(RecordType)(0),               // 0: gophkeeper.v1.RecordType
	(*Record)(nil),                // 1: gophkeeper.v1.Record
	(*EncryptedRecordData)(nil),   // 2: gophkeeper.v1.EncryptedRecordData
	(*CreateRecordRequest)(nil),   // 3: gophkeeper.v1.CreateRecordRequest
	(*GetRecordRequest)(nil),      // 4: gophkeeper.v1.GetRecordRequest
	(*ListRecordsRequest)(nil),    // 5: gophkeeper.v1.ListRecordsRequest
	(*ListRecordsResponse)(nil),   // 6: gophkeeper.v1.ListRecordsResponse
	(*UpdateRecordRequest)(nil),   // 7: gophkeeper.v1.UpdateRecordRequest
	(*DeleteRecordRequest)(nil),   // 8: gophkeeper.v1.DeleteRecordRequest
	(*DeleteRecordResponse)(nil),  // 9: gophkeeper.v1.DeleteRecordResponse
	(*RecordResponse)(nil),        // 10: gophkeeper.v1.RecordResponse
	(*SyncRecordsRequest)(nil),    // 11: gophkeeper.v1.SyncRecordsRequest
	(*SyncRecordsResponse)(nil),   // 12: gophkeeper.v1.SyncRecordsResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_gophkeeper_v1_vault_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.v1.Record.type:type_name -> gophkeeper.v1.RecordType
	13, // 1: gophkeeper.v1.Record.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: gophkeeper.v1.Record.updated_at:type_name -> google.protobuf.Timestamp
	13, // 3: gophkeeper.v1.Record.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 4: gophkeeper.v1.EncryptedRecordData.type:type_name -> gophkeeper.v1.RecordType
	2,  // 5: gophkeeper.v1.CreateRecordRequest.data:type_name -> gophkeeper.v1.EncryptedRecordData
	1,  // 6: gophkeeper.v1.ListRecordsResponse.records:type_name -> gophkeeper.v1.Record
	2,  // 7: gophkeeper.v1.UpdateRecordRequest.data:type_name -> gophkeeper.v1.EncryptedRecordData
	1,  // 8: gophkeeper.v1.DeleteRecordResponse.record:type_name -> gophkeeper.v1.Record
	1,  // 9: gophkeeper.v1.RecordResponse.record:type_name -> gophkeeper.v1.Record
	1,  // 10: gophkeeper.v1.SyncRecordsResponse.records:type_name -> gophkeeper.v1.Record
	3,  // 11: gophkeeper.v1.VaultService.CreateRecord:input_type -> gophkeeper.v1.CreateRecordRequest
	4,  // 12: gophkeeper.v1.VaultService.GetRecord:input_type -> gophkeeper.v1.GetRecordRequest
	5,  // 13: gophkeeper.v1.VaultService.ListRecords:input_type -> gophkeeper.v1.ListRecordsRequest
	7,  // 14: gophkeeper.v1.VaultService.UpdateRecord:input_type -> gophkeeper.v1.UpdateRecordRequest
	8,  // 15: gophkeeper.v1.VaultService.DeleteRecord:input_type -> gophkeeper.v1.DeleteRecordRequest
	11, // 16: gophkeeper.v1.VaultService.SyncRecords:input_type -> gophkeeper.v1.SyncRecordsRequest
	10, // 17: gophkeeper.v1.VaultService.CreateRecord:output_type -> gophkeeper.v1.RecordResponse
	10, // 18: gophkeeper.v1.VaultService.GetRecord:output_type -> gophkeeper.v1.RecordResponse
	6,  // 19: gophkeeper.v1.VaultService.ListRecords:output_type -> gophkeeper.v1.ListRecordsResponse
	10, // 20: gophkeeper.v1.VaultService.UpdateRecord:output_type -> gophkeeper.v1.RecordResponse
	9,  // 21: gophkeeper.v1.VaultService.DeleteRecord:output_type -> gophkeeper.v1.DeleteRecordResponse
	12, // 22: gophkeeper.v1.VaultService.SyncRecords:output_type -> gophkeeper.v1.SyncRecordsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_vault_proto_init() }
func file_gophkeeper_v1_vault_proto_init() {
	if File_gophkeeper_v1_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_vault_proto_rawDesc), len(file_gophkeeper_v1_vault_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_v1_vault_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_vault_proto_depIdxs,
		EnumInfos:         file_gophkeeper_v1_vault_proto_enumTypes,
		MessageInfos:      file_gophkeeper_v1_vault_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_vault_proto = out.File
	file_gophkeeper_v1_vault_proto_goTypes = nil
	file_gophkeeper_v1_vault_proto_depIdxs = nil
}
